### ISSUE TITLE
./unbound_exporter.go:451:28: undefined: prometheus.Handler

### ISSUE THREAD

**Issue by Warlock667** [kumina/unbound_exporter#14]
Hi @all,

during the make I get the following error:

./unbound_exporter.go:451:28: undefined: prometheus.Handler

Does anyone have a hint for me how I can fix this ? Unfortunaly I have no clue about Golang.

Thanks a lot in advance !

**Comment by gochito** [comment]
Same issue here

**Comment by gochito** [comment]
I DL the code and changed prometheus.Handler to promhttp.Handler and it worked. 
Working on a RbPi 3B, Go 1.9 .

**Comment by Warlock667** [comment]
Unfortunaly that didn't work for me. Attached you will find a diff of the original file and the patched file, just in case I didn't get your hind right.


./unbound_exporter.go:451:28: undefined: promhttp
root@lemmy:~/go/src/github.com/kumina/unbound_exporter# diff unbound_exporter.go unbound_exporter.go.orig
451c451
<       http.Handle(*metricsPath, promhttp.Handler())
---
>       http.Handle(*metricsPath, prometheus.Handler())

**Comment by pgporada** [comment]
Have you all tried building with this PR? https://github.com/kumina/unbound_exporter/pull/13

**Comment by gochito** [comment]
I did not, but basically I imported the Prometheus golang libraries in my go installation, and then changed the 451 line as is shown in the PR... got it working fine ....It should work for Warlock667

**Comment by Warlock667** [comment]
@pgporada - Thanks a lot ! PR? #13 worked absolutely fine in my case :-)

**Comment by Ivaylo-Korakov** [comment]
Thank you all! I just made a new release v0.2 with the fix.
